name: "Feature request"
description: "Propose an improvement or new capability"
title: "[Feature]: "
labels: ["type: feature", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea with RapidKit 🚀
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain point does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred approach.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who benefits and how?
